# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call(`_myscreening_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_myscreening_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_myscreening_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_myscreening_rcpparma_bothproducts`, x)
}

rcpp_ols <- function(x, y, n) {
    .Call(`_myscreening_rcpp_ols`, x, y, n)
}

